# APP_STAND
# MINIO_API_DOMAIN
# MINIO_CONSOLE_DOMAIN
# MINIO_VERSION_TAG
# S3_ACCESS_KEY_ID
# S3_SECRET_ACCESS_KEY

name: gen2chat

networks:
  qliqy-network:
    name: qliqy-network
    external: true
  traefik-network:
    name: traefik-network
    external: true

volumes:
  minio-data:
    name: minio-data
  minio-certs:
    name: minio-certs

x-logging:
  &formatted-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    max-size: "10m"
    max-file: "3"
    mode: "non-blocking"
    max-buffer-size: "4m"

services:
  minio:
    container_name: minio
    image: minio/minio:${MINIO_VERSION_TAG:-RELEASE.2025-04-22T22-12-26Z}
    restart: always
    labels:
      - traefik.enable=true

      # Admin console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      - traefik.http.services.minio-console.loadbalancer.passhostheader=true
      - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_DOMAIN:-minio.gen2b.ai}`)
      - traefik.http.routers.minio-console.entrypoints=https
      - traefik.http.routers.minio-console.tls=true
      - traefik.http.routers.minio-console.tls.certresolver=le-${APP_STAND}
      - traefik.http.routers.minio-console.service=minio-console

      # S3 API
      - traefik.http.services.minio-api.loadbalancer.server.port=9000
      - traefik.http.services.minio-api.loadbalancer.passhostheader=true
      - traefik.http.routers.minio-api.rule=Host(`${MINIO_API_DOMAIN:-s3.gen2b.ai}`)
      - traefik.http.routers.minio-api.entrypoints=https
      - traefik.http.routers.minio-api.tls=true
      - traefik.http.routers.minio-api.tls.certresolver=le-${APP_STAND}
      - traefik.http.routers.minio-api.service=minio-api
    healthcheck:
      test: curl -f http://0.0.0.0:9000/minio/health/live
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
      MINIO_DEFAULT_BUCKETS: 'gen2chat'
      MINIO_SERVER_URL: https://${MINIO_API_DOMAIN:-s3.gen2b.ai}
    command: >-
      minio
      server
      /data
      --console-address ":9001"
      --address ":9000"
    volumes:
      - minio-data:/data
      - minio-certs:/certs
    logging: *formatted-logging
    networks: [qliqy-network, traefik-network]
